# Config file for automatic testing at travis-ci.org
language: python
dist: xenial
sudo: true
env:
    global:
        - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
        - SEGFAULT_SIGNALS=all
        - DEVELOPMENT=false
matrix:
    fast_finish: true
    include:
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.7"
          env: TOXENV=py37
        - python: "3.8"
          env: TOXENV=py38
        # - python: "3.6"
        #   env: TOXENV=check
cache:
    directories:
        - $HOME/.cache/pip
before_install:
    - python --version
    - uname -a
    - lsb_release -a
    - pip install codecov
install:
    - pip install tox
    - virtualenv --version
    - easy_install --version
    - pip --version
    - tox --version
script:
    - tox -v
after_success:
    - tox -e report
    - coverage xml
    - python-codacy-coverage -r coverage.xml
    - codecov
after_failure:
    - more .tox/log/* | cat
    - more .tox/*/log/* | cat
notifications:
    email:
        on_success: never
        on_failure: always
